[package]
name = "cinga"
version = "0.1.0"
authors = ["Thandile Nododile <6636345e@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
